---
- name: Install Ansible
  hosts: all
  become: true

  tasks:
    - name: Update apt-get
      ansible.builtin.apt:
        update_cache: true

    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install Ansible
      ansible.builtin.pip:
        name: ansible
        state: present
