- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
  when: ansible_os_family == 'Debian'

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  when: ansible_os_family == 'Debian'

- name: Change docker logger to json-file
  ansible.builtin.lineinfile:
    path: /etc/docker/daemon.json
    line: '{"log-driver": "json-file"}'
  when: ansible_os_family == 'Debian'

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when: ansible_os_family == 'Debian'
